name: bikeshare_streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - geopy
  - pip:
      - streamlit==1.34.0
      - folium==0.16.0
      - streamlit-folium==0.22.1
      - geopandas==0.13.2
      - altair==5.3.0
      - requests==2.32.0
      - pyautogui==0.9.53
      - branca==0.7.2
      - click==8.1.7
      - jinja2==3.1.4
      - pillow==9.2.0
      - protobuf==4.25.3
      - pyarrow==16.1.0
      - pydeck==0.9.1
      - rich==13.7.1
      - tenacity==8.3.0
      - watchdog==4.0.0